### ISSUE TITLE
create a BACK button on the detailed page so that user can go back to the search results

### ISSUE THREAD

**Issue by jaya1983** [CHAUDHARYS1/book-lovers#38]

**Comment by CHAUDHARYS1** [comment]
I'll have to see which back button you are referring too. I added the logo as a back button or "home" button.

**Comment by mehak-zehra** [comment]
@CHAUDHARYS1 I think she wanted a back button on detailed page so user can go back to list page. Logo is going back to home page where they can't see the list. @jaya1983 please correct me If I'm wrong.
